[package]
name = "lcf-rs"
version = "0.1.0"
edition = "2024"
description = "A library for working with the Lcf file format used by RPG Maker 2000 games."
repository = "https://github.com/AcrylonitrileButadieneStyrene/lcf-rs"
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["rpgmaker2000", "r2k", "lcf"]
categories = ["encoding"]

[dependencies]
thiserror = "2.0"
nom = "8.0"
derive_builder = "0.20.2"
log = "0.4.27"

[dependencies.serde]
version = "1.0"
features = ["derive"]
